  - name: Start rancher master node
    ec2:
      image: "{{ template }}"
      instance_type: "{{ instance_type_master }}"
      spot_price: "{{ bid_master }}"
      spot_wait_timeout: "{{ wait_timeout }}"
      key_name: "{{ ssh_key }}"
      group: "{{ security_group_name }}"
      region: "{{ aws_region }}"
      vpc_subnet_id: "{{ vpc.subnets[1].id }}"
      zone: "{{ availability_zone }}"
      assign_public_ip: yes
      user_data: "{{ lookup('template', '../templates/master.j2') }}"
      wait: yes
    when: num_hosts_master | int == 0
    register: master
 
  - debug: msg='rancher master IP is {{ item.public_ip }}'
    with_items: master.instances

  - name: Add new instance to host group
    add_host: hostname={{ item.public_ip }} groupname=master
    with_items: master.instances

  - name: Start rancher workers
    ec2:
      image: "{{ template }}"
      instance_type: "{{ instance_type }}"
      spot_price: "{{ bid }}"
      spot_wait_timeout: "{{ wait_timeout }}"
      key_name: "{{ ssh_key }}"
      group: "{{ security_group_name }}"
      region: "{{ aws_region }}"
      vpc_subnet_id: "{{ vpc.subnets[1].id }}"
      zone: "{{ availability_zone }}"
      assign_public_ip: yes
      user_data: "{{ lookup('template', '../templates/worker.j2') }}"
      count: "{{ num_nodes }}"
      wait: yes
    when: num_hosts_workers | int != num_nodes
    register: ec2

  - name: Add new instance to host group
    add_host: hostname={{ item.public_ip }} groupname=worker
    with_items: ec2.instances

  - name: Wait for SSH to come up
    wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
    with_items: ec2.instances
